server:
  port: 8761

spring:
  application:
    name: discovery-server
#Eureka configuration
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

#Log Pattern
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

